---
version: '3.4'
services:
  ${acs.host}:
    image: acs-create-user-cloud:development
    build:
      dockerfile: ./Dockerfile
      context: ../../create-user-cloud-platform-docker/target
    environment:
      CATALINA_OPTS : "-agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n"
    volumes:
      - create-user-cloud-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - ${db.host}
    ports:
      - 8000:8000
    networks:
      - backend

  ${share.host}:
    image: share-create-user:development
    build:
      dockerfile: ./Dockerfile
      context: ../../create-user-cloud-share-docker/target
    environment:
      REPO_HOST: ${acs.host}
      REPO_PORT: 8080
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${db.host}:
    image: ${docker.postgres.image}:${docker.postgres.version}
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - create-user-cloud-db-volume:/var/lib/postgresql/data
    networks:
      - backend

  ${solr.host}:
    image: ${docker.solr.image}:${docker.solr.version}
    environment:
      SOLR_ALFRESCO_HOST: ${acs.host}
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: ${solr.host}
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    volumes:
      - create-user-cloud-solr-contentstore-volume:/opt/alfresco-search-services/contentstore
      - create-user-cloud-solr-data-volume:/opt/alfresco-search-services/data
      - create-user-cloud-solr-keystores-volume:/opt/alfresco-search-services/keystores
      - create-user-cloud-solr-solrhome-volume:/opt/alfresco-search-services/solrhome
    depends_on:
      - ${acs.host}
    networks:
      - backend

  ${nginx.host}:
    image: nginx-create-user-cloud:development
    build:
      dockerfile: ./Dockerfile
      context: ../../create-user-cloud-nginx-docker/target
    environment:
      PORT: 8080
      PROXY_HOST: http://${public.host}:${public.port}
    ports:
      - ${public.port}:8080
    depends_on:
      - ${acs.host}
      - ${share.host}
    networks:
      - backend

volumes:
  create-user-cloud-acs-volume:
  create-user-cloud-db-volume:
  create-user-cloud-solr-contentstore-volume:
  create-user-cloud-solr-data-volume:
  create-user-cloud-solr-keystores-volume:
  create-user-cloud-solr-solrhome-volume:

networks:
  backend:
